export const colleges = [
    "IIT Madras",
    "IIT Delhi",
    "IIT Bombay",
    "IIT Kanpur",
    "IIT Kharagpur",
    "IIT Roorkee",
    "IIT Guwahati",
    "IIT Hyderabad",
    "IIT (BHU) Varanasi",
    "IIT (ISM) Dhanbad",
    "IIT Indore",
    "IIT Gandhinagar",
    "IIT Ropar",
    "IIT Bhubaneswar",
    "IIT Jodhpur",
    "IIT Mandi",
    "IIT Patna",
    "IIT Tirupati",
    "IIT Jammu",
    "IIT Palakkad",
    "IIT Bhilai",
    "IIT Dharwad",
    "IIT Goa",
    "Dr. B.R. Ambedkar NIT (NIT Jalandhar)",
    "Malaviya NIT (MNIT Jaipur)",
    "Maulana Azad NIT (MANIT Bhopal)",
    "Motilal Nehru NIT (MNNIT Allahabad)",
    "NIT Agartala",
    "NIT Andhra Pradesh",
    "NIT Arunachal Pradesh",
    "NIT Calicut",
    "NIT Delhi",
    "NIT Durgapur",
    "NIT Patna",
    "Sardar Vallabhbhai NIT (NIT Surat)",
    "NIT Meghalaya",
    "NIT Raipur",
    "NIT Srinagar",
    "NIT Kurukshetra",
    "NIT Manipur",
    "NIT Mizoram",
    "NIT Nagaland",
    "NIT Hamirpur",
    "NIT Silchar",
    "NIT Uttarakhand",
    "VNIT Nagpur",
    "NIT Rourkela",
    "NIT Warangal",
    "NIT Surathkal",
    "Manipal Institute of Technology",
    "Symbiosis International University",
    "BITS Pilani (Goa Campus)",
    "Amity University, Noida",
    "St. Xavier's College",
    "Vellore Institute of Technology, chennai (VIT)",
    "SRCC", 
    "Hansraj", "Miranda House", 
    "Indira Gandhi Delhi Technical University for Women",
    "Dayanand Sagar University",
    "Indian Institute of Science (IISc)",
    "St. Stephen's College",
    "Indian Institute of Management (IIM) Ahmedabad",
    "National Law School of India University (NLSIU)",
    "Lady Shri Ram College for Women",
    "Ashoka University",
    "Thiagarajar College of Engineering",
    "Chandigarh University",
    "Christ University",
    "PSG College of Technology",
    "Loyola College",
    "Presidency College",
    "Madras Christian College",
    "Fergusson College",
    "St. Joseph's College",
    "Ramanujan College",
    "Queen Mary's College",
    "Shivaji College",
    "Maharaja's College",
    "St. Teresa's College",
    "St. Aloysius College",
    "Jamal Mohamed College",
    "Kristu Jayanti College",
    "Bishop Heber College",
    "Government Arts College",
    "Sri Ramakrishna College of Arts and Science",
    "St. Xavier's College",
    "Dyal Singh College",
    "Hans Raj College",
    "Kirori Mal College",
    "Hindu College",
    "Deshbandhu College",
    "Atma Ram Sanatan Dharma College",
    "Shaheed Rajguru College of Applied Sciences for Women",
    "Lady Irwin College",
    "Jesus & Mary College",
    "Sri Guru Gobind Singh College of Commerce",
    "Techno Main Salt Lake",
    "Delhi Technical Campus",
    "Bengal Institute of Technology",
    "Heritage Institute of Technology",
    "Maharaja Agrasen Institute of Technology",
    "Maharaja Surajmal Institute of Technology",
    "IIIT kalyani",
    "IIIT Delhi",
    "IIIT Hyderabad",
    "IIEST shibpur",
    "Jadavpur University",
    "UPES, Dehradun",
    "Vellore Institute of Technology(VIT), Vellore",
    "SRM, chennai"
]
