name: Sync to Fork

on:
  push:
    branches:
      - main

jobs:
  sync:
    runs-on: ubuntu-latest

    permissions: {}

    steps:
      - name: Checkout source
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.FORK_TOKEN }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build
        run: bun run build

      - name: Push changes to fork
        run: |
          git config --global user.name "dsuper03ASM"
          git config --global user.email "your-email@example.com"
          git remote add fork https://dsuper03ASM:${{ secrets.FORK_TOKEN }}@github.com/dsuper03ASM/zynvo-main.git
          git push --force fork main
